### ISSUE TITLE
Not starting on Ubuntu 21.10

### ISSUE THREAD

**Issue by Sush-ruta** [Elagoht/Whatsapp-Qt5#1]
After I click on the Whatsapp icon, nothing starts. Trying to open via terminal by typing `whatsapp-qt5` gives the following output:

```
~$ whatsapp-qt5
./Whatsapp: line 1: version: command not found
./Whatsapp: line 2: oid: command not found
size: '160220616': No such file
```

I'm probably doing something wrong, so any help would be appreciated. I am so looking forward to trying a non-electron Whatsapp client on Linux!

**Comment by Elagoht** [comment]
I recently installed Arch, And I also couldn't start it. I wrote this program for my needs and now I still need it. I'll fix it soon.

**Comment by Elagoht** [comment]
Sorry for this issue. It was my first try with git-lfs. I didn't track the application so it didn't upload. It fixed. More feature will be added.
